SELECT * FROM dbo.STORE WHERE StoreName LIKE '%marsano%'
SELECT * FROM dbo.VENDOR
SELECT * FROM dbo.USERS

SELECT TOP 30 *
FROM dbo.STORE
ORDER BY StoreID ASC;


SELECT 
    COLUMN_NAME, 
    DATA_TYPE, 
    CHARACTER_MAXIMUM_LENGTH,
    NUMERIC_PRECISION,
    NUMERIC_SCALE
FROM 
    INFORMATION_SCHEMA.COLUMNS
WHERE 
    TABLE_NAME = 'USERS';